GET http://localhost:8080/users/
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKb3Jud2VyIn0.an8PzenP-yXt1zRA4Zqhn6ahDO9ke_HS6ABvfvZ-ojg

###
POST http://localhost:8080/users/update/75
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKb3Jud2VyIn0.an8PzenP-yXt1zRA4Zqhn6ahDO9ke_HS6ABvfvZ-ojg

{
  "username": "Suicide",
  "password": "1234",
  "email": "test@mail2.com",
  "firstName": "hi",
  "lastName": "death",
  "organizationId": 15
}

###
POST http://localhost:8080/organizations/update/5
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKb3Jud2VyIn0.an8PzenP-yXt1zRA4Zqhn6ahDO9ke_HS6ABvfvZ-ojg
Content-Type: application/json

{
  "name": "Hi-Inc",
  "type": "Food industry"
}

###
GET http://localhost:8080/organizations
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKb3Jud2VyIn0.an8PzenP-yXt1zRA4Zqhn6ahDO9ke_HS6ABvfvZ-ojg

###
POST http://localhost:8080/decisions/update/5
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKb3Jud2VyIn0.an8PzenP-yXt1zRA4Zqhn6ahDO9ke_HS6ABvfvZ-ojg
Content-Type: application/json

{
  "name": "Test1_EDIT",
  "description": "РусскеУкраинске",
  "strategyList": ["first","second","third"],
  "natureStatesCounter": 3,
  "organizationId": 15,
  "createdDate": 1619870990.000000000
}

###
DELETE http://localhost:8080/organizations/15
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKb3Jud2VyIn0.an8PzenP-yXt1zRA4Zqhn6ahDO9ke_HS6ABvfvZ-ojg
Content-Type: application/json

###
GET http://localhost:8080/decisions
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKb3Jud2VyIn0.an8PzenP-yXt1zRA4Zqhn6ahDO9ke_HS6ABvfvZ-ojg

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "Jornwer",
  "password": "qwertyuiop"
}

